CREATE TABLE IF NOT EXISTS Customers(	
	customer_id SERIAL PRIMARY KEY,
	customer_name VARCHAR(40),
	gender VARCHAR(5),
	age INT,
	city VARCHAR(30),
	state VARCHAR(30),
	signup_date DATE
);

CREATE TABLE IF NOT EXISTS Products(
	product_id SERIAL PRIMARY KEY,
	product_name VARCHAR(30),
	category VARCHAR(30),
	brand VARCHAR(30),
	price NUMERIC(10,2),
	cost_price NUMERIC(10,2)
	
);

CREATE TABLE IF NOT EXISTS  Orders(					
	order_id SERIAL PRIMARY KEY,				
	customer_id INT REFERENCES Customers(customer_id),				
	product_id INT REFERENCES Products(product_id),				
	order_date DATE,				
	quantity INT				
							
);

SELECT * FROM Customers;
SELECT * FROM Products;
SELECT * FROM Orders;

-- I USE DIRECT METHOD TO IMPORT DATA

--1).Find all customers who belong to Uttar Pradesh.
SELECT * 
FROM Customers
WHERE state ='Uttar Pradesh';

--2).Find all products whose price is greater than ₹50,000.
SELECT *
FROM Products
WHERE price >50000;

--3).Display products belonging to the Electronics category.
SELECT * 
FROM Products
WHERE category='Electronics';

--4).Count the total number of customers.
SELECT COUNT(customer_id) AS TOTAL_CUSTOMERS
FROM Customers;
-- IT HAS 500 RECORDS

--5).Count the total number of PRODUCTS.
SELECT COUNT(product_id) AS TOTAL_PRODUCTS
FROM Products;
-- IT HAS 100 RECORDS

--6).Count the total number of ORDERS.
SELECT COUNT(order_id) AS TOTAL_ORDERS
FROM Orders;
-- IT HAS 5000 RECORDS

--7).Find the highest-priced product.
SELECT * 
FROM Products
ORDER BY price DESC
LIMIT 1;
-- PRODUCT_ID 59 SONY FURNITURE 

--8).Find the lowest-priced product.
SELECT * 
FROM Products
ORDER BY price 
LIMIT 1;
-- IT IS PRODUCT_ID 27 IKEA FASHION

--9).Find the average product price.
SELECT AVG(price) AS AVERAGE_PRICE 
FROM Products;


--Intermediate Level
--10).Find the total revenue generated from all orders.
SELECT SUM(p.price *o.quantity)AS TOTAL_REVENUE
FROM Products p
JOIN
Orders o
ON o.product_id=p.product_id;

--11).Find the total quantity sold across all orders.
SELECT SUM(quantity) AS TOTAL_QUANTITY
FROM Orders;

--12).List the top 10 customers who placed the highest number of orders.
SELECT c.customer_name, c.age, c.city,o.quantity
FROM Orders o 
JOIN
 Customers c
 ON o.customer_id= c. customer_id
 ORDER BY o.quantity DESC
 Limit 10;
 
--13).Find the top 10 customers by total spending.
SELECT c.customer_id,c.customer_name,SUM(p.price * o.quantity) AS TOTAL_SPENT
FROM Customers c 
JOIN Orders o
ON c.customer_id= o.customer_id
JOIN
products p
ON p.product_id= o.product_id
GROUP BY c.customer_id, c.customer_name
ORDER BY TOTAL_SPENT  DESC
LIMIT 10;

--14).Display the top 10 best-selling products based on quantity sold.
SELECT p.product_id, p.product_name, 
SUM(o.quantity) AS TOTAL_QUANTITY
FROM orders o
JOIN products p
ON p.product_id= o.product_id
GROUP BY p.product_id, p.product_name
ORDER BY TOTAL_QUANTITY DESC
LIMIT 10;

--15).Find the top 10 products generating the highest revenue.
SELECT p.product_id, p.product_name, 
SUM(p.price *o.quantity) AS TOTAL_REVENUE
FROM orders o
JOIN products p
ON p.product_id= o.product_id
GROUP BY p.product_id, p.product_name
ORDER BY TOTAL_REVENUE DESC
LIMIT 10; 

--16).Calculate revenue generated by each category.
SELECT p.category, 
SUM(p.price *o.quantity) AS TOTAL_REVENUE
FROM orders o
JOIN products p
ON p.product_id= o.product_id
GROUP BY p.category; 

--17).Calculate revenue generated by each state.
SELECT c.state, 
SUM(p.price *o.quantity) AS TOTAL_REVENUE
FROM orders o
JOIN products p
ON p.product_id= o.product_id
JOIN customers c
ON o.customer_id=c.customer_id
GROUP BY c.state
ORDER BY TOTAL_REVENUE;  

--18).Calculate revenue generated by each city.
SELECT c.city, 
SUM(p.price *o.quantity) AS TOTAL_REVENUE
FROM orders o
JOIN products p
ON p.product_id= o.product_id
JOIN customers c
ON o.customer_id=c.customer_id
GROUP BY c.city
ORDER BY TOTAL_REVENUE;

--19).Find the average order value.
 SELECT AVG(order_value) AS average_order_value
FROM
(
SELECT order_id,
SUM(p.price * o.quantity) AS order_value
FROM Orders o
JOIN Products p
ON o.product_id = p.product_id
GROUP BY order_id
) x;

--20).Identify customers who have never placed an order.
SELECT c.customer_id, c.customer_name
FROM customers c
 LEFT JOIN orders o
ON o.customer_id= c.customer_id
WHERE o.order_id IS NULL;

--21).Identify products that have never been ordered.
SELECT p.product_id, p.product_name
FROM products p
 LEFT JOIN orders o
ON o.product_id= p.product_id
WHERE o.order_id IS NULL;

--22).Find customers who have placed more than 5 orders.
SELECT c.customer_id, c.customer_name,
COUNT(order_id) AS TOTAL_ORDERS
FROM customers c
 LEFT JOIN orders o
ON o.customer_id= c.customer_id
GROUP BY c.customer_name, c.customer_id
HAVING COUNT(order_id)> 5;

--23).Find the category with the highest revenue.
SELECT p.category,SUM(p.price*o.quantity) AS REVENUE
FROM products p
 JOIN orders o
ON o.product_id= p.product_id
GROUP BY p.category
ORDER BY REVENUE DESC 
LIMIT 1;
-- IT IS ELECTRONICS

--24).Find the brand with the highest revenue.
SELECT p.brand,SUM(p.price*o.quantity) AS REVENUE
FROM products p
 JOIN orders o
ON o.product_id= p.product_id
GROUP BY p.brand
ORDER BY REVENUE DESC 
LIMIT 1;
-- IT IS SONY


--Advanced Level
--25).Rank customers based on total revenue generated.
SELECT c.customer_id, c.customer_name,
SUM(p.price*o.quantity) AS total_revenue,
RANK() OVER(ORDER BY SUM(p.price * o.quantity) desc) AS ranking
FROM orders o
JOIN
customers c
ON o.customer_id= c.customer_id
JOIN products p
ON p.product_id= o.product_id
GROUP BY c.customer_id, c.customer_name;

--26).Rank products based on revenue generated.
SELECT p.product_id, p.product_name,
SUM(p.price*o.quantity) AS total_revenue,
RANK() OVER(ORDER BY SUM(p.price * o.quantity) desc) AS ranking
FROM orders o
JOIN products p
ON p.product_id= o.product_id
GROUP BY p.product_id,p.product_name ;

--27).Find the top-selling product in each category.
SELECT *
FROM
(
SELECT p.category,
p.product_name,
SUM(o.quantity) AS total_quantity,
RANK() OVER(
PARTITION BY p.category
ORDER BY SUM(o.quantity) DESC
) AS rank_no
FROM Products p
JOIN Orders o
ON p.product_id = o.product_id
GROUP BY p.category, p.product_name
) x
WHERE rank_no = 1;

--28).Find the highest-spending customer in each state.
SELECT *
FROM
(
SELECT c.state,
c.customer_name,
SUM(p.price * o.quantity) AS revenue,
RANK() OVER(
PARTITION BY c.state
ORDER BY SUM(p.price * o.quantity) DESC
) AS rank_no
FROM Customers c
JOIN Orders o
ON c.customer_id = o.customer_id
JOIN Products p
ON o.product_id = p.product_id
GROUP BY c.state, c.customer_name
) x
WHERE rank_no = 1;

--29).Calculate monthly revenue.
SELECT DATE_TRUNC('month',o.order_date) AS MONTH,
SUM(p.price*o.quantity) AS REVENUE
FROM orders o
JOIN products p
ON o.product_id= p.product_id
GROUP BY MONTH;

--30).Calculate quarterly revenue.
SELECT EXTRACT(QUARTER FROM o.order_date) AS QUARTER,
SUM(p.price*o.quantity) AS REVENUE
FROM orders o
JOIN products p
ON o.product_id= p.product_id
GROUP BY QUARTER;

--31).Identify the month with the highest revenue.
SELECT DATE_TRUNC('month',o.order_date) AS MONTH,
SUM(p.price*o.quantity) AS REVENUE
FROM orders o
JOIN products p
ON o.product_id= p.product_id
GROUP BY MONTH
ORDER BY REVENUE DESC
LIMIT 1;

--32).Identify the month with the lowest revenue.
SELECT DATE_TRUNC('month',o.order_date) AS MONTH,
SUM(p.price*o.quantity) AS REVENUE
FROM orders o
JOIN products p
ON o.product_id= p.product_id
GROUP BY MONTH
ORDER BY REVENUE 
LIMIT 1;

--33).Calculate month-over-month revenue growth.   SAME AS QUESTION 313
SELECT DATE_TRUNC('month', o.order_date) AS month,
SUM(p.price * o.quantity) AS revenue
FROM orders o
JOIN products p
ON o.product_id = p.product_id
GROUP BY month
ORDER BY month;

--34).Calculate the running total revenue by month.
SELECT DATE_TRUNC('month', o.order_date) AS month,
SUM(p.price * o.quantity) AS revenue
FROM orders o
JOIN products p
ON o.product_id = p.product_id
GROUP BY month
ORDER BY month;

--35).Determine the revenue contribution percentage of each category.
SELECT p.category,
SUM(p.price * o.quantity) AS revenue
FROM orders o
JOIN products p
ON o.product_id = p.product_id
GROUP BY p.category
ORDER BY revenue DESC;

--36).Find the top 20% of customers contributing to total revenue.
SELECT c.customer_id,c.customer_name,
SUM(p.price * o.quantity) AS revenue
FROM orders  o
JOIN customers c
ON c.customer_id = o.customer_id
JOIN products p
ON o.product_id = p.product_id
GROUP BY c.customer_id
ORDER BY revenue DESC
LIMIT 20;

--36).Classify customers into High, Medium, and Low value segments based on spending.
SELECT c.customer_name,SUM(p.price* o.quantity) AS TOTAL_REVENUE,
CASE WHEN SUM(p.price* o.quantity)>500000 THEN'HIGH'
WHEN SUM(p.price* o.quantity)>200000 THEN'MEDIUM'
ELSE'LOW'
END AS category
FROM customers c
JOIN orders o
ON c.customer_id= o.customer_id
JOIN products p
ON p.product_id= o.product_id
GROUP BY c.customer_name;

--Business Scenario Questions

--37).The marketing team wants to target the most valuable customers. Identify the top 20 customers by spending.
SELECT c.customer_id,c.customer_name,
SUM(p.price * o.quantity) AS total_spending
FROM customers c
JOIN
orders o
ON c.customer_id = o.customer_id
JOIN 
products p
ON o.product_id = p.product_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_spending DESC
LIMIT 20;

--38).Management wants to know which states generate the most revenue. Prepare a state-wise revenue report.
SELECT c.state,SUM(p.price * o.quantity) AS revenue
FROM customers c
JOIN
orders o
ON c.customer_id = o.customer_id
JOIN 
products p
ON o.product_id = p.product_id
GROUP BY c.state
ORDER BY revenue DESC;
-- maximum - uttar pradesh

--39).The inventory team wants to focus on high-performing products. Identify the top-selling products.
SELECT p.product_id,p.product_name,
SUM(o.quantity) AS total_quantity
FROM products p
JOIN 
orders o
ON p.product_id = o.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_quantity DESC;

--40).The finance team wants to understand category performance. Generate a category-wise revenue report.
SELECT p.product_id,p.product_name,
SUM(o.quantity) AS total_quantity
FROM products p
JOIN 
orders o
ON p.product_id = o.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_quantity DESC;

--41).The sales manager wants to know the best-performing month of the year.
SELECT DATE_TRUNC('month', o.order_date) AS month,
SUM(p.price * o.quantity) AS revenue
FROM orders o
JOIN 
products p
ON o.product_id = p.product_id
GROUP BY month
ORDER BY revenue DESC
LIMIT 1;

--42).Identify repeat customers who placed multiple orders.
SELECT c.customer_id,c.customer_name,
COUNT(o.order_id) AS total_orders
FROM customers c
JOIN 
orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
HAVING COUNT(o.order_id) > 1;

--43).Identify one-time customers who placed only one order.
SELECT c.customer_id,c.customer_name,
COUNT(o.order_id) AS total_orders
FROM customers c
JOIN 
orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
HAVING COUNT(o.order_id) = 1;

--44).Find the average revenue generated per customer.
SELECT AVG(customer_revenue) AS avg_revenue_per_customer
FROM
(
SELECT c.customer_id,
SUM(p.price * o.quantity) AS customer_revenue
FROM customers c
JOIN 
orders o
ON c.customer_id = o.customer_id
JOIN 
products p
ON o.product_id = p.product_id
GROUP BY c.customer_id
) x;

--45).Determine which category contributes the largest share of revenue.
SELECT p.category,
SUM(p.price * o.quantity) AS revenue
FROM products p
JOIN
orders o
ON p.product_id = o.product_id
GROUP BY p.category
ORDER BY revenue DESC
LIMIT 1;

--46).Generate a report showing customer name, total orders, total quantity purchased, and total revenue generated.
SELECT c.customer_name,COUNT(o.order_id) AS TOTAL_ORDER,
SUM(o.quantity) AS TOTAL_QUANTITY, SUM(p.price*o.quantity) AS TOTAL_REVENUE
FROM orders o
JOIN customers c
ON o.customer_id= c.customer_id
JOIN
products p
ON o.product_id= p.product_id
GROUP BY c.customer_name;